// Generated by CoffeeScript 1.3.3
(function() {

  require.config({
    shim: {
      underscore: {
        exports: '_'
      },
      backbone: {
        deps: ['underscore', 'jquery'],
        exports: 'Backbone'
      }
    },
    paths: {
      text: 'lib/require/text',
      jquery: 'lib/jquery',
      underscore: 'lib/underscore',
      backbone: 'lib/backbone'
    }
  });

  require([], function() {
    return alert('hi!');
  });

}).call(this);
