// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['views/set_time', 'views/set_alarm', 'text!templates/home.html'], function(homeTemplate, SetTimeView, SetAlarmView) {
    var HomeView;
    return HomeView = (function(_super) {

      __extends(HomeView, _super);

      function HomeView() {
        return HomeView.__super__.constructor.apply(this, arguments);
      }

      HomeView.prototype.el = '#container';

      HomeView.prototype.template = homeTemplate;

      HomeView.prototype.events = {
        'click #time': function() {
          return (new SetTimeView()).render();
        },
        'click #alarm': function() {
          return (new SetAlarmView()).render();
        },
        'click #weather': function() {
          return $('#weather-form').toggle();
        }
      };

      HomeView.prototype.render = function() {
        $(this.el).html(this.template);
        return this;
      };

      return HomeView;

    })(Backbone.View);
  });

}).call(this);
