// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['text!templates/home_sub.html'], function(templateHomeSub) {
    var HomeSubView;
    return HomeSubView = (function(_super) {

      __extends(HomeSubView, _super);

      function HomeSubView() {
        return HomeSubView.__super__.constructor.apply(this, arguments);
      }

      HomeSubView.prototype.tagName = 'div';

      HomeSubView.prototype.events = {
        'click button': function() {
          return this.toggleContent();
        }
      };

      HomeSubView.prototype.initialize = function(id, label, content) {
        this.id = id;
        return this.template = _.template(templateHomeSub)({
          label: label,
          content: content
        });
      };

      HomeSubView.prototype.render = function() {
        this.$el.html(this.template);
        this.toggleContent();
        return this;
      };

      HomeSubView.prototype.toggleContent = function() {
        return this.$('#content').toggle();
      };

      return HomeSubView;

    })(Backbone.View);
  });

}).call(this);
