// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['text!templates/time.html'], function(timeTemplate) {
    var TimeView;
    return TimeView = (function(_super) {

      __extends(TimeView, _super);

      function TimeView() {
        return TimeView.__super__.constructor.apply(this, arguments);
      }

      TimeView.prototype.el = '#time-view';

      TimeView.prototype.template = timeTemplate;

      TimeView.prototype.render = function() {
        $(this.el).html(this.template);
        return this;
      };

      return TimeView;

    })(Backbone.View);
  });

}).call(this);
